# Appendix: {-}

```{=latex}
\markboth{Appendix}{Appendix}
```

Additional resources, as well as all code, files to replicate the present
work can be found on its
[GitHub repository](https://github.com/BBieri/Thesis). The repository
is currently private but feel free to reach out via
[email](mailto:bernhard.bieri@graduateinstitute.ch) to get access.

All code files are located in the R/ folder and are labeled according to the
order in which they should be executed. I.e. the first file to run would be the
`0_Setup.R` file followed by the files in the `1_DataPreparation` folder.
When executing the scripts, you might need to install/load particular versions
of the loaded packages. These are indicated in comments next to the
corresponding `library()` call in the corresponding file.
If you have any specific questions regarding the replication of the thesis,
please also feel free to reach out via
[email](mailto:bernhard.bieri@graduateinstitute.ch).

Below are the robustness checks for the two linear models testing the Weak
Porter Hypothesis. These models have been reestimated following the exclusion
of the United States, Japan, and Germany which are three outlier countries
in terms of innovation. We observe that results are robust to their exclusion.

```{=latex}
\begin{table}[h!]
\centering
\begin{adjustbox}{width=0.5\textwidth}
\begin{tabular}{lcc|cc}
   \toprule
    & R\&D & Patents & R\&D & Patents\\
   Model & \multicolumn{2}{c}{FDSM} & \multicolumn{2}{c}{SDSM} \\ 
                         & (1)           & (2)           & (3)           & (4)\\  
   \midrule 
   ln EPS (t-1)          & -0.04         & -0.02         & -0.05         & -0.08\\   
                         & (0.06)        & (0.10)        & (0.07)        & (0.12)\\   
   ln Strength (t-1)     & -0.05         & 0.06          & 0.08          & 0.15$^{*}$\\   
                         & (0.11)        & (0.11)        & (0.07)        & (0.08)\\   
   ln Transitivity (t-1) & -0.13         & 0.74$^{*}$    & 0.31          & 0.39$^{**}$\\   
                         & (0.28)        & (0.42)        & (0.22)        & (0.18)\\   
   ln GDP per cap        & 0.49          & 1.9$^{***}$   & 0.32          & 2.0$^{***}$\\   
                         & (0.35)        & (0.37)        & (0.37)        & (0.37)\\   
   ln ExportIntensity  & 0.05          & 0.65$^{***}$  & 0.10          & 0.73$^{***}$\\   
                         & (0.17)        & (0.20)        & (0.19)        & (0.19)\\   
   ln ImportIntensity  & 0.39$^{*}$    & -0.73$^{**}$  & 0.25          & -1.0$^{***}$\\   
                         & (0.21)        & (0.30)        & (0.25)        & (0.32)\\   
    \\
   Observations          & 478           & 477           & 421           & 421\\  
   Within R$^2$          & 0.0569        & 0.2302        & 0.0573        & 0.2776\\  
   F-test                & 118.0         & 137.5         & 139.0         & 173.7\\  
    \\
   Year fixed effects    & $\checkmark$  & $\checkmark$  & $\checkmark$  & $\checkmark$\\   
   Country fixed effects & $\checkmark$  & $\checkmark$  & $\checkmark$  & $\checkmark$\\   
   \bottomrule
\end{tabular}
\end{adjustbox}
\par \raggedright 
\footnotesize{All models are estimated using Ordinary Least Squares. Newey-West corrected standard errors in parentheses. * significant 10\%, ** significant 5\%, *** significant 1\%.}
\par
\caption{Weak Porter Hypothesis without United States, Japan, and Germany (1 year lag)}
\label{tab:RobChecklag1}
\end{table}
```

```{=latex}
\begin{table}[h!]
\centering
\begin{adjustbox}{width=0.5\textwidth}
\begin{tabular}{lcc|cc}
   \toprule
    & R\&D & Patents & R\&D & Patents\\
   Model & \multicolumn{2}{c}{FDSM} & \multicolumn{2}{c}{SDSM} \\ 
                         & (1)           & (2)           & (3)           & (4)\\  
   \midrule 
   ln EPS (t-5)          & 0.16$^{**}$   & -0.14$^{*}$   & 0.15$^{**}$   & -0.22$^{***}$\\   
                         & (0.06)        & (0.08)        & (0.06)        & (0.07)\\   
   ln Strength (t-5)     & -0.13         & -0.03         & -0.11$^{**}$  & 0.008\\   
                         & (0.07)        & (0.08)        & (0.05)        & (0.06)\\   
   ln Transitivity (t-5) & 0.48          & 0.12          & 0.29$^{*}$    & 0.64$^{***}$\\   
                         & (0.30)        & (0.35)        & (0.15)        & (0.17)\\   
   log(GDPCapita)        & 0.27          & 2.1$^{***}$   & 0.20          & 2.1$^{***}$\\   
                         & (0.37)        & (0.35)        & (0.37)        & (0.36)\\   
   log(ExportIntensity)  & 0.25          & 0.78$^{***}$  & 0.30          & 0.84$^{***}$\\   
                         & (0.19)        & (0.21)        & (0.18)        & (0.25)\\   
   log(ImportIntensity)  & 0.26          & -1.1$^{***}$  & 0.18          & -1.0$^{***}$\\   
                         & (0.25)        & (0.28)        & (0.28)        & (0.28)\\   
    \\
   Observations          & 452           & 451           & 385           & 384\\  
   Within R$^2$          & 0.0950        & 0.2630        & 0.0989        & 0.3055\\  
   F-test                & 133.9         & 153.5         & 167.5         & 180.5\\  
    \\
   Year fixed effects    & $\checkmark$  & $\checkmark$  & $\checkmark$  & $\checkmark$\\   
   Country fixed effects & $\checkmark$  & $\checkmark$  & $\checkmark$  & $\checkmark$\\   
   \bottomrule
\end{tabular}
\end{adjustbox}
\par \raggedright 
\footnotesize{All models are estimated using Ordinary Least Squares. Newey-West corrected standard errors in parentheses. * significant 10\%, ** significant 5\%, *** significant 1\%.}
\par
\caption{Weak Porter Hypothesis without United States, Japan, and Germany (5 year lag)}
\label{tab:RobChecklag5}
\end{table}
```
