---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Thesis

This repository contains the replication code to replicate the thesis
titled "The Impact of Global Environmental Governance on Innovation;
Revisiting the Porter Hypothesis at the International Level" by Bernhard Bieri
in fulfillment of the Master in International Economics of the Geneva Graduate
Institute.

## How to replicate this thesis:

All code files are located in the `R/` folder and are labeled according to the
order in which they should be executed. I.e., the first file to run would be the
`0_Setup.R` file followed by the files in the `1_DataPreparation` folder.

When executing the scripts, one might need to install/load particular versions
of the loaded packages. These are indicated in comments next to the corresponding
`library()` call in the respective file.

Finally, note that due to dataset size, we were not able to upload the datasets
used to compute patent counts. These are available
[on request](mailto:bernhard.bieri@graduateinstitute.ch).

- Quick links:
  - Final PDF: [click here]()
  - Centrality computation: [click here](https://github.com/BBieri/Thesis/blob/main/R/1_DataPreparation/2_YearlyCentrailty.R)
  - Econometric analysis: [click here](https://github.com/BBieri/Thesis/blob/main/R/2_Analysis/0_PanelAnalysis.R)

## Got any questions?

Feel free to reach out to me at the following
[email address](mailto:bernhard.bieri@graduateinstitute.ch) if you have any
questions or inquiries.
